import React from "react";
import { BrowserRouter as Router, Route } from "react-router-dom";
import * as Dashboards from "../views/dashboards";
import { Box } from "@chakra-ui/react";

export default function AdminRouters(show: boolean) {
  return (
    <div>
      <Router>
        <Box
          alignItems="center"
          justifyContent="center"
          backgroundColor="#f4f4f4"
        >
          <Route
            path="/admin/tambah-state"
            exact
            component={Dashboards.TambahState}
          />
          <Route
            path="/admin/tambah-pic"
            exact
            component={Dashboards.TambahPIC}
          />
          <Route
            path="/admin/edit-state/:stateID"
            exact
            component={Dashboards.EditState}
          />
          <Route
            path="/admin/daftar-state"
            exact
            component={Dashboards.DaftarState}
          />
          <Route
            path="/admin/daftar-pic"
            exact
            component={Dashboards.DaftarPIC}
          />
          <Route
            path="/admin/state-detail/:stateID"
            exact
            component={Dashboards.StateDetail}
          />
          <Route
            path="/admin/daftar-maba"
            exact
            component={Dashboards.DaftarMahasiswaBaru}
          />
          <Route
            path="/admin/detail-maba/:nim"
            exact
            component={Dashboards.DetailMahasiswaBaru}
          />
          <Route
            path="/admin/daftar-home"
            exact
            component={Dashboards.DaftarHome}
          />
          <Route
            path="/admin/edit-home/:search_key"
            exact
            component={Dashboards.EditHome}
          />
          <Route
            path="/admin/tambah-home"
            exact
            component={Dashboards.TambahHome}
          />
          <Route
            path="/admin/tambah-media"
            exact
            component={Dashboards.TambahMedia}
          />
          <Route
            path="/admin/tambah-mahasiswa"
            exact
            component={Dashboards.TambahMahasiswa}
          />
          <Route
            path="/admin/tambah-panitia"
            exact
            component={Dashboards.TambahPanitia}
          />
          <Route
            path="/admin/tambah-organisator"
            exact
            component={Dashboards.TambahOrganisator}
          />
          <Route
            path="/admin/daftar-mahasiswa"
            exact
            component={Dashboards.DaftarMahasiswa}
          />
          <Route
            path="/admin/daftar-panitia"
            exact
            component={Dashboards.DaftarPanitia}
          />
          <Route
            path="/admin/daftar-organisator"
            exact
            component={Dashboards.DaftarOrganisator}
          />
          <Route
            path="/admin/edit-mahasiswa/:nim"
            exact
            component={Dashboards.EditMahasiswa}
          />
          <Route
            path="/admin/edit-akun"
            exact
            component={Dashboards.EditAkun}
          />
          <Route path="/admin" exact component={Dashboards.LandingDashboard} />
        </Box>
      </Router>
    </div>
  );
}
