export {
  TambahState,
  DaftarState,
  StateDetail,
  EditState,
  TambahPIC,
  DaftarPIC,
  DaftarHome,
  EditHome,
  TambahHome,
  TambahMedia,
  DaftarNarasi,
  EditNarasi,
  TambahMahasiswa,
  TambahPanitia,
  TambahOrganisator,
  DaftarMahasiswa,
  DaftarPanitia,
  DaftarOrganisator,
  EditMahasiswa,
  EditAkun,
  DaftarMahasiswaBaru,
  DetailMahasiswaBaru,
  LandingDashboard,
} from "./admin";
